### PR TITLE
Renaming hasPermission to userHasPermission

### PR DESCRIPTION
**Pull request by githubjeka**
```php
$accessChecker->hasPermission($id, 'update', $params);
```

Now it read as `accessChecker has permission` .  May be better read as `user has permission`

```php
$accessChecker->userHasPermission($id, 'update', $params);
```

Or rewrite all to
```php
class User implements UserAccessChecker {

    public function hasPermission(string $permissionName, array $parameters = []): bool
    {

    }
}
```

### CODE REVIEW

**Comment by demonking** [comment]
It's an Interface, you cannot call it directly

`$accessChecker->hasPermission($id, 'update', $params);`

**Comment by githubjeka** [comment]
I know.

It is access checker interface but his metod describe user and relation with the user behavior but naming as `hasPermission`, not access manager behavior.

Better to rename method `hasPermission` to `userHasPermission` for used in user context.

Or create access manager interface without context hasPermission :
```php
<?php
namespace Yiisoft\Access;
/**
 * For more details and usage information on AccessCheckerInterface, see
 * the [guide article on security authorization](guide:security-authorization).
 */
interface AccessCheckerInterface
{
    /**
     * Checks if object has the specified permission.
     *
     * @param string $permissionName the name of the permission to be checked against.
     * @param array $parameters name-value pairs that will used to determine if access is granted.
     *
     * @return bool whether object has the specified permission.
     * @throws \InvalidArgumentException if any of argument is not of the expected type or does not refer to an existing value
     */
    public function hasPermission(string $permissionName, array $parameters = []): bool;
}

```

**Comment by samdark** [comment]
I like initial idea. Indeed, that naming is better.

**Comment by samdark** [comment]
Merged. Thanks!

**Pull request merged**
